sudo: required

environment:
  - DOCKER_IMAGE=rezme/resume-core-api
  - GIT_TAG=null

services:
  - docker

# check if the image within this tag already exists
before_install:
  - export GIT_TAG=`git tag | tail -n1`
  - curl -s https://hub.docker.com/v2/repositories/$DOCKER_IMAGE/tags/$GIT_TAG/ -I | grep -i "200 OK" && echo tag already exists && true

# # builds the image
# install:
#   - docker-compose -f docker-compose.travis.yml build

# # pushes to registry
# script:
#   - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
#   - docker push $DOCKER_IMAGE:latest
#   - docker push $DOCKER_IMAGE:$GIT_TAG
#   - docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$GIT_TAG
